### ISSUE TITLE
IRQL NOT LESS OR EQUAL

### ISSUE THREAD

**Issue by twindragon6** [ViGEm/BthPS3#1]
Hopefully this information helps, if not I can dig around and find what your after or reproduce the issue. The bluetooth adapter is a BCM20702A0 with driver V12.0.1.921
[logs.zip](https://github.com/ViGEm/BthPS3/files/5800114/logs.zip)

**Comment by Cornysz** [comment]
BSOD? I got this BSOD yesterday with same error code too. Got it after stopping shibari service with Control + C. Already reported to Nefarius via discord.

**Comment by localhost127001** [comment]
Same here. Two cases IRQL NOT LESS OR EQUAL and one  Kernel Auto Boost Lock Acquisition With Raised IRQL. I don't know is it related or not

**Comment by nefarius** [comment]
Thanks but crucial information is lacking. What driver version? What OS version? What architecture? Happens when doing what exactly? Info, info, info!

**Comment by nefarius** [comment]
A crash creates a memory dump in `C:\Windows\memory.dmp` right after the crash reboot. I'd need that file (probably a few hundred megs so compress it= over a confidential channel - preferably on the Discord - as it can contain sensitive information and must not be shared in public.

**Comment by nefarius** [comment]
Check out v1.3.72, should be fixed.

**Comment by twindragon6** [comment]
Fixed in V1.3.72
