### ISSUE TITLE
Windows on ARM, Support?

### ISSUE THREAD

**Issue by sidd-kishan** [ViGEm/BthPS3#13]
Please let us know when can we have an ARM64 version for Windows on ARM OS.

**Comment by nefarius** [comment]
Never, as long as I'm doing this alone and fuelled by a donation every now and then, I don't own any ARM hardware and therefore have no interest or means to port/compile/support for that platform.

**Comment by sidd-kishan** [comment]
We at Windows on Rasberry Pi community have ported windows on arm to Rasberry pi 4 b+ we can help you with the testing. If your efforts are good we can try to start a crowdfunding campaign for you.

**Comment by nefarius** [comment]
I think my countless past efforts speak for themselves 😉 is there more I can read about this community and said efforts?

**Comment by nefarius** [comment]
Good news to the two people possibly reading this: I got my first ARM64 device and will tinker with it soon 😄

**Comment by nefarius** [comment]
So the ARM64 driver builds work fine but the distribution of a working setup will be tricky [as it appears that no official stable WiX with ARM64 support exists yet](https://github.com/wixtoolset/issues/issues/6269) 🙁 

So we either wait or switch to Advanced Installer 🤔

**Comment by nefarius** [comment]
Ah, digging a bit through the related issues it's claimed that [WiX 3.14](https://wixtoolset.org/releases/v3-14-0-712/) (a pre-release?) offers ARM64 support, will try to install that and see what happens 🤞

**Comment by nefarius** [comment]
> Ah, digging a bit through the related issues it's claimed that [WiX 3.14](https://wixtoolset.org/releases/v3-14-0-712/) (a pre-release?) offers ARM64 support, will try to install that and see what happens 🤞

Outdated link, [this release](https://wixtoolset.org/releases/v3-14-0-6526/) ships with ARM64 SDK libs 👀

**Comment by nefarius** [comment]
Currently battling with CI to build the ARM64 components the setup depends on 🤞

**Comment by nefarius** [comment]
Signing...

![image](https://user-images.githubusercontent.com/286631/185445440-9ae387fe-ad47-4eb5-89bd-a665d5f66f6e.png)

**Comment by nefarius** [comment]
[Release](https://github.com/ViGEm/BthPS3/releases/tag/v2.5.148.0) 🥳
