### ISSUE TITLE
KERNEL AUTO BOOST LOCK ACQUISITION WITH RAISED IRQL [BSOD]

### ISSUE THREAD

**Issue by Cornysz** [ViGEm/BthPS3#2]
BSOD after stopped Shibari, this is my second time appear BSOD after stopping Shibari service.
Any driver information/version should I attach? Thank you in advance

[Raised IRQL.zip](https://github.com/ViGEm/BthPS3/files/5803602/Raised.IRQL.zip)

NB : In the first BSOD, the stop code is IRQL NOT LESS OR EQUAL, I can't find the log.

**Comment by nefarius** [comment]
There is no log. A crash creates a memory dump in `C:\Windows\memory.dmp` right after the crash reboot. I'd need that file (probably a few hundred megs so compress it= over a confidential channel - preferably on the Discord - as it can contain sensitive information and must not be shared in public.

**Comment by nefarius** [comment]
Since and with which version does it happen?

**Comment by Cornysz** [comment]
> Since and with which version does it happen?

I got that error since I updated newest version of BthPS3 (v1.3.65), before that my laptop never encountered by BSOD.
BTW I've sent you friend request, for sending memory.dmp via direct message (discord)

**Comment by nefarius** [comment]
Thanks, I found the issue and am providing a fix soon.

**Comment by nefarius** [comment]
This has been fixed with v1.3.72
