### ISSUE TITLE
RUMBLE NOT WORKING PANHAI CONTROLLER

### ISSUE THREAD

**Issue by jacksauciboie** [ViGEm/BthPS3#23]
The controller worked with SCP for a bit (latest version) and then it stopped i tried old SCP wtih DLL fix by some guy it worked but i got lazy since it's annoying to turn on again via bluetooth and also no vibration
with Latest SCP ver i can get rumble via USB but controller doesn't work with bluetooth like i said
i tried BthPS3 and the controller works automatically with bluetooth but there is no rumble should i give up? xD

**Comment by nefarius** [comment]
Wrong place to ask for support, no useful info provided, closed.
