### ISSUE TITLE
Driver Picking up Stray Controllers

### ISSUE THREAD

**Issue by BoneRattler** [ViGEm/BthPS3#29]
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://vigem.org/Community-Support/
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Driver software is picking up other DS3 controllers that aren't mine.

### Steps to reproduce
- Start any unpaired DS3 near computer.

**Actual result:** Other family member's controller connecting to my pc.
**Expected result:** Only my controller should connect.

### Machine info

**CPU-Architecture:** x64
**Windows version:** Windows 10 10.0.19042
**Software/driver version(s):** Unsure

### Other Info
We found this out entirely by mistake. I only ever use my controller with my pc. I went to my family member's room, who was trying to connect their controller to their pc, and heard noise from mine as if something connected. Found out both controllers are able to connect with my pc, but I've never done anything with the other controller to connect it with this machine.

**Comment by nefarius** [comment]
That's nothing the driver can influence. The controller connects to whatever host radio MAC is written to its flash memory, so the only case where controllers start to connect to hosts they're not supposed to is duplicated host radio MAC addresses, which happens rather frequently if you use wide spread cheap dongles. [Try changing the MAC of your PC to a new random value](https://macaddresschanger.com/) and see if that helps.

Cheers
