### ISSUE TITLE
Save the time stamp of the last connection request and the associated device's Name and MAC Address as properties/keys

### ISSUE THREAD

**Issue by Kanuan** [ViGEm/BthPS3#45]
90% of the time that a controller can't connect to the BT Adapter running with BthPS3 it's because either the controller is using an unsupported name, it's a known name for an unsupported controller or the connection request is not even reaching the adapter.

Currently, investigating these cases require a full driver tracing. By adding the last device's Name, Mac Address and time stamp of the connection as properties/registry keys so they can be displayed on the BthPS3 Config App would greatly facilitate troubleshooting BT related connection issues.

**Comment by nefarius** [comment]
An alternative would to write to the event log but the procedure is so annoyingly verbose... but it would be quite useful, also easier for everybody than abusing the registry and having to integrate in the UI.
