### ISSUE TITLE
Broke "DS4Windows" mode in DsHidMini

### ISSUE THREAD

**Issue by nefarius** [ViGEm/BthPS3#49]
Regression reported by @Kanuan that wireless DS4Windows mode on DsHidMini broke wit the refactoring changes.

**Comment by nefarius** [comment]
@Kanuan is `04:98:F3:91:3F:CE` the MAC address of the controller you tested with? Can you please confirm, thanks.

**Comment by Kanuan** [comment]
yes

![image](https://user-images.githubusercontent.com/24910442/184503630-ab54b04d-c9d2-41e1-8941-32d268aafbcd.png)

**Comment by nefarius** [comment]
What an odd issue indeed, I have fixed the Device ID format in my local test build but it still doesn't work 🤔

**Comment by nefarius** [comment]
I'll focus on the crash-relevant fixes and then come back to this once I have a new production signed copy I can then debug directly with DS4Windows.

**Comment by nefarius** [comment]
Found it. DS4Windows checks if a detected controller is a virtual device to exclude them from detection and it so happens that the current check now also triggers on the DS3:

![image](https://user-images.githubusercontent.com/286631/184711201-d2fbda8a-ee0f-40dc-80ed-df0189acccb1.png)

Thinking on what's the best way to fix this, IMHO the detection in DS4Windows should be patched since this check method is very brittle to begin with. More to come.

**Comment by nefarius** [comment]
Success!

![image](https://user-images.githubusercontent.com/286631/186663013-23402969-4517-4184-b338-440543ee4c47.png)

Preparing PR.

**Comment by nefarius** [comment]
The fix has been merged into DS4Windows 🥳 Now we wait for a new release ☕

**Comment by nefarius** [comment]
[A fixed version has been released](https://github.com/Ryochan7/DS4Windows/releases/tag/v3.1.6).
