### ISSUE TITLE
Unable to install BthPS3

### ISSUE THREAD

**Issue by Necrow51** [ViGEm/BthPS3#54]
Hello, I wanted to do an uninstallation and reinstallation but impossible
![Capture d’écran 2022-08-30 190951](https://user-images.githubusercontent.com/88400526/187499201-83e675d9-80a8-43ed-b1e3-04fe1581c8d5.png)
Yet everything is well deleted in my drivers
![Sans titre 2](https://user-images.githubusercontent.com/88400526/187499786-216dd10f-9a6a-4c15-9e8d-f9585bf21034.jpg)
So I'm completely stuck :(

**Comment by nefarius** [comment]
[Found and documented the solution](https://vigem.org/projects/BthPS3/Frequently-Asked-Questions/#how-to-fix-previous-version-found-on-reinstall)!
