### ISSUE TITLE
 problem trying to install bthps3 on windows 7 64 bit

### ISSUE THREAD

**Issue by martingamer128** [ViGEm/BthPS3#60]
My problem is that I was trying to install BTHPS3 on a PC with Windows 7 64 bits because on my PC with Windows 11 it didn't work and the installer said the following:
Nefariurs BTHPS3 Bluetooth Drivers Setup Wizard ended Prematurely
![Captura de pantalla 2022-11-30 162125](https://user-images.githubusercontent.com/69813847/204889280-7ecaeb74-9458-4d8d-85fb-5aa2d080afae.png)
Attached install log file
[install.txt](https://github.com/ViGEm/BthPS3/files/10127198/install.txt)

**Comment by nefarius** [comment]
You folks never cease to amaze me.... And not in a positive way.

![image](https://user-images.githubusercontent.com/286631/204905994-0bfab59b-7611-4a7c-8302-f95090b443cc.png)
