### ISSUE TITLE
Vibration/Rumble bug

### ISSUE THREAD

**Issue by shenk-i** [ViGEm/BthPS3#71]
----------------------------------------
I experience this bug when using DualShock 3 in bluetooth mode, in native PC games and in RPCS3 as well.
Basicly what is happeing is that when a vibration need to happen it does but the controller doesnt stop vibrating until i perform an action again which triggers a vibration.

I am using a USB Bluetooth dongle, and this "bug" doesnt happen when using a cable to play with DualShock 3

**Comment by nefarius** [comment]
[This is explained here](https://vigem.org/projects/DsHidMini/Output-Rate-Control-Explained/), which is as good as it gets.

**Comment by shenk-i** [comment]
Thanks for the fast response! I'll check it out!
