### ISSUE TITLE
Trouble uninstalling

### ISSUE THREAD

**Issue by tiag0d** [ViGEm/BthPS3#72]
Hey I installed the software without running into any error messages and after restarting my computer as requested by the installer my bluetooth dongle wasn't working.

Now I wanted to reinstall the software to see if it fixes but when I hit uninstall I get a error message saying "Bluetooth Host Radio not found. A working Bluetooth stack is required for driver installation or removal."

Is there another way to uninstall this program?

**Comment by nefarius** [comment]
https://vigem.org/projects/BthPS3/Frequently-Asked-Questions/

**Comment by ellie12134** [comment]
that link doesnt work anymore, what was even the solution?

**Comment by nefarius** [comment]
https:// docs.nefarius.at/projects/BthPS3/Frequently-Asked-Questions/

Not that hard to find.
