### ISSUE TITLE
Conflict with Dualshock 4 on Bluetooth (connection error)

### ISSUE THREAD

**Issue by Mihail856** [ViGEm/BthPS3#75]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://vigem.org/Community-Support/
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When installing BthPS3, the dualshok4 bluetooth connection stopped working (I need to use dualshok3 and dualshok4 at the same time). Windows says that the gamepad is connected, but after a second the connection disappears. dualshok4 itself continues to blink while waiting for connection.

There is a funny situation that dualshok4 connects via Bluetooth and everything works, but only as a new device (if it has never been connected before or it has been deleted in Bluetooth devices). But with subsequent automatic connections, the failure described above occurs.

Before installing BthPS3, I could automatically connect dualshock 4 via bluetooth. And also I could use dualshock 3 via USB after installing DsHidMini. I use DS4Windows and all gamepads were displayed correctly there.

### Steps to reproduce
- Installed BthPS3
- Installed DsHidMini
- Launched DsHidMini
- Connected dualshock3 via USB (the error is reproduced without this action)
- A connection was established with dualshock3 (the error is reproduced without this action)
- Disconnected dualshock3 from USB (the error is reproduced without this action)
- Connected dualshock3 via Bluetooth (the error is reproduced without this action)
- Turning on dualshock 4
- I search for devices in the windows bluetooth settings
- Connecting dualshock 4 (windows remembers the device)
- To check, I disable dualshock 4
- Turning on dualshock 4 again
- There is an automatic connection (an error occurs here)

**Actual result:** 
Windows writes that dualshock 4 is connected, but after a second the connection is disconnected. And dualshock 4 continues to flash the indicator while waiting for connection.
**Expected result:** 
DualShock 4 automatically connects to a PC via bluetooth

### Screenshots
I can take screenshots (if necessary), but they won't be able to convey much information. I tried to write the error in some detail.

### Machine info
**CPU-Architecture:** x64
**Windows version:** Windows 10 Pro 22H2
**Software/driver version(s):** v2.6.174

### Any other helpful information
**DS4Windows version(s):** v3.2.10
**DsHidMini Driver:** v2.2.282

I have an assumption that BthPS3 perceives dualshock4 as dualshock3 and tries to transmit connection information to it (although I connect via the standard bluetooth settings tools in windows). As I read, the driver intercepts bluetooth traffic and splits it to connect dualshock3. But dualshock4 does not expect this and the connection fails.

**Comment by nefarius** [comment]
Oh my goodness, please read the FAQ, could've saved you and me the troubles wasting time writing and reading this.
